name: Deploy Workflow

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      SCENARIO:
        required: true
        type: string

permissions:
  id-token: write
  contents: read      

jobs:
  run-test-scenario:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    env:
      ACCOUNT_ID_VAR_PREFIX: 'AWS_ACCOUNT_ID_'

    steps:
      - name: set variables dynamically
        run: |
          echo "AWS_ACCOUNT_ID_VAR=${{ env.ACCOUNT_ID_VAR_PREFIX }}" >> $GITHUB_ENV

      - name: Use dynamic variable
        AWS_ACCOUNT_ID: ${{AWS_ACCOUNT_ID_VAR}}${{imputs.ENV}}
        run: |
          echo "${{AWS_ACCOUNT_ID }}"
