name: Deploy Workflow

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      SCENARIO:
        required: true
        type: string

permissions:
  id-token: write
  contents: read      

jobs:
  run-test-scenario:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    env:
      ACCOUNT_ID_VAR_PREFIX: 'AWS_ACCOUNT_ID_'

    steps:
      - name: set variables dynamically
        run: |
          echo AWS_ACCOUNT_ID='${{ env.ACCOUNT_ID_VAR_PREFIX }}''${{inputs.ENV}}' >> $GITHUB_ENV
          echo ACCOUNT='${{vars.AWS_ACCOUNT_ID}}' >> $GITHUB_ENV

      - name: Use dynamic variable
        run: |
          echo "${{env.ACCOUNT}}"
