name: Deploy Workflow

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      SCENARIO:
        required: true
        type: string

permissions:
  id-token: write
  contents: read      

jobs:
  run-test-scenario:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    env:
      ACCOUNT_ID_VAR: 'AWS_ACCOUNT_ID_'${{ inputs.ENVIRONMENT }}

    steps:
      - name: set variables dynamically
        run: |
          echo "AWS_ACCOUNT_ID=${{ env.ACCOUNT_ID_VAR }}" >> $GITHUB_ENV

      - name: Use dynamic variable
        run: |
          echo "AWS ACCUNT ID: $AWS_ACCOUNT_ID"
